{% set version = "0ae27c81ea6b326e165c553786531086bb4dd13d" %}
{% set sha256 = "942b4dda73222ad44feebd826916e8db993a76cb5a10579274e3446bfebef1e2" %}

{% set build = 0 %}

package:
  name: moby2
  version: {{ version }}

source:
  url: https://github.com/ACTCollaboration/moby2/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - complex_fftw.patch

build:
  number: {{ build }}
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - llvm-openmp # [osx]
  host:
    - llvm-openmp # [osx]
    - libgomp # [linux]
    - libopenblas * *openmp*
    - libblas * *openblas
    - python
    - setuptools
    - fftw
    - gsl
    - libactpol
    - future
    - numpy
    - scipy
    # Although not a dependency, we put numba here to force
    # building with a numba-compatible numpy version
    - numba
    # Not a dependency, force installing a NaMaster-compatible GSL version
    #- namaster
  run:
    - llvm-openmp # [osx]
    - libopenblas * *openmp*
    - libblas * *openblas
    - {{ pin_compatible("scipy") }}
    - {{ pin_compatible("fftw") }}
    - {{ pin_compatible("libopenblas") }}
    - {{ pin_compatible("libblas") }}
    - {{ pin_compatible("gsl") }}
    - {{ pin_compatible("libactpol") }}
    - python
    - future
    - matplotlib
    - astropy
    - ephem
    - pytz

test:
  imports:
    - moby2

about:
  home: https://github.com/ACTCollaboration/moby2
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python tools for ACT
  description: |
    This is a conda package for moby2
  dev_url: https://github.com/ACTCollaboration/moby2

extra:
  recipe-maintainers:
    - tskisner
